apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  selector:
    matchLabels:
      run: app2
  replicas: 1
  template:
    metadata:
      labels:
        run: app2
    spec:
      containers:
      - name: app2
        image: nginx:stable-alpine
        ports:
        - containerPort: 80