---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-deployment
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: hello-world
    spec:
      containers:
      - name: hello
        image: nginx:stable-alpine
        ports:
        - containerPort: 80