apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  selector:
    matchLabels:
      run: hello-deployment
  replicas: 1
  template:
    metadata:
      labels:
        run: hello-deployment
    spec:
      containers:
      - name: hello-deployment
        image: nginx:stable-alpine
        ports:
        - containerPort: 80