apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-simple
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: notif-demo-argocd
spec:
  destination:
    name: 'in-cluster'
    namespace: 'argocd'
  source:
    path: ./argocd/apps/demo-simple-apps/
    repoURL: 'https://github.com/elmustapha-doumghordi/onepercent.git'
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
  project: onepercent