apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-simplesimple
spec:
  destination:
    name: 'in-cluster'
    namespace: 'argocd'
  source:
    path: ./apps/demo-simple-apps/
    repoURL: 'https://github.com/elmustapha-doumghordi/onepercent.git'
    targetRevision: master
  project: onepercent